### ISSUE TITLE
executing examples/submit_file.py on local instance of snovault 

### ISSUE THREAD

**Issue by annashch-insitro** [ENCODE-DCC/snovault#313]
Hello, I have snovault running on an ec2 vm on localhost:6543 
I am attempting to execute https://github.com/ENCODE-DCC/snovault/blob/dev/examples/submit_file.py to store metadata for an example fastq. I get an authentication error: 

```ubuntu@ip-172-31-158-56:~/snovault/examples$ python submit_file.py
Calculating md5sum.
Validating file.
Submitting metadata.
Submission failed: 401 Unauthorized
{"@type": ["HTTPUnauthorized", "Error"], "status": "error", "code": 401, "title": "Unauthorized", "description": "This server could not verify that you are authorized to access the document you requested.  Either you supplied the wrong credentials (e.g., bad password), or your browser does not understand how to supply the credentials required."}
Traceback (most recent call last):
  File "submit_file.py", line 154, in <module>
    r.raise_for_status()
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://localhost:6543/file
```

I am assuming the issue is here https://github.com/ENCODE-DCC/snovault/blob/dev/examples/submit_file.py#L14 (encoded_access_key and encoded_secret_access_key).  How do I determine what goes into these fields? My AWS keys are not working. 

Thank you!

**Comment by keenangraham** [comment]
Wow, that's a pretty old file that I'm not sure anyone uses anymore so can't say it works as expected (I think most submitters use https://github.com/StanfordBioinformatics/encode_utils now, but not sure it translates). 

In general when posting/patching/getting anything that requires authentication you should add an access key to a user's profile. Not sure `snovault` looks exactly the same but on portal it looks like this (I deleted this key):

<img width="766" alt="Screen Shot 2020-12-22 at 9 49 46 AM" src="https://user-images.githubusercontent.com/16053922/102918018-0dc97d80-443b-11eb-8a5e-1b335b7516d5.png">

<img width="1234" alt="Screen Shot 2020-12-22 at 9 39 04 AM" src="https://user-images.githubusercontent.com/16053922/102917955-ef638200-443a-11eb-80b1-b7bff8531662.png">

Then you can use that access key and secret access key to gain the same permissions as the user. In Python you can pass these keys to `requests`. 

Change `status` property of `file` object:
```
import requests
auth = ('access_key', 'secret_access_key')
r = requests.patch('https://www.encodeproject.org/files/ENCFF262VBW/', json={'status': 'released'}, auth=auth)
```

Get (private) file properties:
```
r = requests.get('https://www.encodeproject.org/files/ENCFF321LTI/', auth=auth)
print(r.json())
```

I'm assuming if you just generate an access key you can copy it into that script. It looks like it is eventually used in `post`: https://github.com/ENCODE-DCC/snovault/blob/b935f223d18dbb9dfeb663543afd3c9f2761c39f/examples/submit_file.py#L150
